version: '3.9'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - ./docker.env
    volumes:
      - ./:/app

  db:
    container_name: db
    image: mysql:latest
    restart: always
    env_file:
      - ./docker.env
    volumes:
      - data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:alpine
    restart: always

volumes:
  data:
