version: '3.9'

services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    env_file:
      - ./docker.env
    volumes:
      - data:/var/lib/mysql

  app:
    container_name: app
    build: .
    depends_on:
      - db
    env_file:
      - ./docker.env
    volumes:
      - ./:/app

volumes:
  data:
